### ISSUE TITLE
EMJobService有报错，空指针很多

### ISSUE THREAD

**Issue by privatestring** [HyphenateInc/Hyphenate-SDK-Android#2]
# main
java.lang.NullPointerException
Attempt to invoke virtual method 'int com.android.server.job.controllers.JobStatus.getUid()' on a null object reference
解析原始
}
1 android.os.Parcel.readException(Parcel.java:1562)
2 android.os.Parcel.readException(Parcel.java:1509)
3 android.app.job.IJobCallback$Stub$Proxy.jobFinished(IJobCallback.java:168)
4 android.app.job.JobService$JobHandler.handleMessage(JobService.java:147)
5 android.os.Handler.dispatchMessage(Handler.java:111)
6 android.os.Looper.loop(Looper.java:224)
7 android.app.ActivityThread.main(ActivityThread.java:5911)
8 java.lang.reflect.Method.invoke(Native Method)
9 java.lang.reflect.Method.invoke(Method.java:372)
10 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
11 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)

**Comment by zhanw** [comment]
Fixed in 3.3.0, use `compile 'com.hyphenate:hyphenate-sdk-lite:3.3.0'` or `compile 'com.hyphenate:hyphenate-sdk:3.3.0'`
