### ISSUE TITLE
3.2.3版本lite sdk 初始化报错，so加载不了

### ISSUE THREAD

**Issue by Charles-ljc** [HyphenateInc/Hyphenate-SDK-Android#3]
java.lang.UnsatisfiedLinkError: dlopen failed: library "libhyphenate_av.so" not found

**Comment by Charles-ljc** [comment]
从jcenter上直接下载的是不行的，从这里下载的是可以的，要同步到jcenter。

**Comment by zhanw** [comment]
清理一下本地缓存，然后再sync下载一遍

**Comment by Charles-ljc** [comment]
还是不行，jcenter上下载的不对，地址：https://jcenter.bintray.com/com/hyphenate/hyphenate-sdk-lite/3.2.3/

**Comment by zhanw** [comment]
怎么清除缓存的，我这边用着litesdk是没问题的，要把本地gradle跟这个库相关的缓存都清理掉

**Comment by Charles-ljc** [comment]
repositories {
    maven { url "https://raw.githubusercontent.com/HyphenateInc/Hyphenate-SDK-Android/master/repository" }
}
gradle配置了这个，清除缓存是可以的，但是jcenter有，不这样配置一样能下载下来，但是jcenter上的包初始化是会报错的，要么就两个地址同步一下，要么就删了jcenter的下载方式，这样很容易误导别人

**Comment by zhanw** [comment]
我现在用的就是jcenter的，jcenter那个是没问题的，让你清除电脑里的缓存是因为jcenter之前上传过有问题的版本，后面修正了但是版本号没变，不清除本地已经下载的内容，gradle不会去下载最新的内容

**Comment by zhanw** [comment]
https://github.com/easemob/livestream_demo_android/tree/dev现在这个正在开发中的项目就是用的jcenter的lite版本

**Comment by zhanw** [comment]
C:\Users\wei\.gradle\caches\modules-2\files-2.1\com.hyphenate\hyphenate-sdk-lite
C:\Users\wei\.m2\repository\com\hyphenate\hyphenate-sdk-lite
这是我windows电脑缓存的路径，你参考删除一下对应的缓存

**Comment by Charles-ljc** [comment]
缓存我都清除了，还是不行，我直接从jcenter上下载的aar里看的代码还是要加载hyphenate_av.so，地址https://jcenter.bintray.com/com/hyphenate/hyphenate-sdk-lite/3.2.3/  ,你下载下来和你本地的比较一下，EMClient.getInstance()方法里调用的loadLibrary()代码

**Comment by zhanw** [comment]
那最直接的报错原因应该不是这个，load里面有try catch，你看下我给你发的链接的那个项目(dev分支)，是正常的

**Comment by liujinchaoDS** [comment]
那个错误是try catch不住的

**Comment by zhanw** [comment]
catch throwable是可以的，你把你项目的armeabi里的文件移动到armeabi-v7a里，把armeabi文件夹删除，完了记得clean，http://docs.easemob.com/doku.php?id=im:200androidclientintegration:160androidreleasenote上个release中把普通arm的so去除了

**Comment by liujinchaoDS** [comment]
我用的arm64-v8a，手机是64位v8a
`private static void loadLibrary() {
        if(!libraryLoaded) {
            try {
                System.loadLibrary("hyphenate_av");
            } catch (Throwable var2) {
                var2.printStackTrace();
            }

            try {
                System.loadLibrary("hyphenate_av_recorder");
            } catch (Throwable var1) {
                var1.printStackTrace();
            }

            System.loadLibrary("hyphenate");
            libraryLoaded = true;
        }

    }`
这是我依赖下来的代码，不报错的代码是
` private static void loadLibrary() {
        if(!libraryLoaded) {
            System.loadLibrary("hyphenate");
            libraryLoaded = true;
        }

    }`

**Comment by Charles-ljc** [comment]
我用的arm64-v8a，手机是64位v8a，依赖下来的代码如下，报java.lang.UnsatisfiedLinkError: dlopen failed: library "libhyphenate_av.so" not found错误
```java
private static void loadLibrary() {
    if(!libraryLoaded) {
        try {
            System.loadLibrary("hyphenate_av");
        } catch (Throwable var2) {
             var2.printStackTrace();
        }
        try {
            System.loadLibrary("hyphenate_av_recorder");
        } catch (Throwable var1) {
            var1.printStackTrace();
        }
        System.loadLibrary("hyphenate");
        libraryLoaded = true;
    }
}
```

不报错的代码是
```java
private static void loadLibrary() {
        if(!libraryLoaded) {
            System.loadLibrary("hyphenate");
            libraryLoaded = true;
        }
 }
```

**Comment by liujinchaoDS** [comment]
我用的arm64-v8a，手机是64位v8a
`private static void loadLibrary() {
if(!libraryLoaded) {
try {
System.loadLibrary("hyphenate_av");
} catch (Throwable var2) {
var2.printStackTrace();
}

    try {
        System.loadLibrary("hyphenate_av_recorder");
    } catch (Throwable var1) {
        var1.printStackTrace();
    }

    System.loadLibrary("hyphenate");
    libraryLoaded = true;
}
}`

这是我依赖下来的代码，不报错的代码是
` private static void loadLibrary() {
if(!libraryLoaded) {
System.loadLibrary("hyphenate");
libraryLoaded = true;
}}`

**Comment by zhanw** [comment]
之前没试64位的机器，刚跑了一下64位的机器确实有问题，我修复一下，好了通知你

**Comment by zhanw** [comment]
fixed,清除缓存sync一下

**Comment by Charles-ljc** [comment]
已解决
